### ISSUE TITLE
GPU training not working

### ISSUE THREAD

**Issue by guccichurch** [Giphy/celeb-detection-oss#4]
Hi
i'd like to do Training & Transfer Learning on my own data using my GPU but it's only using my CPU my GPU utilization 0%
Here is what i have done
- USE_GPU=true in .env
- changed to requirements_gpu.txt in setup.py
Does the tensorflow-gpu version has to be specific one ? can i use latest ?
Any suggestions ?

**Comment by guccichurch** [comment]
i realised that tensorflow-gpu , cudnn , cuda version mismatched and causing problems i fixed this myself closing issue now
